### ISSUE TITLE
连接opengauss5.1报错

### ISSUE THREAD

**Issue by anhuizf1** [dotnetcore/DotNetCore.GaussDB#2]
var connString = "host=192.168.195.138;port=5432;username=admin;password=admin@123;database=irap;";

            var dataSourceBuilder = new GaussDBDataSourceBuilder(connString);
            var dataSource = dataSourceBuilder.Build();

            var conn = await dataSource.OpenConnectionAsync();

            // Insert some data
            await using (var cmd = new GaussDBCommand("INSERT INTO stb006 (usercode,username) VALUES (@p,@p2)", conn))
            {
                cmd.Parameters.AddWithValue("p", "Hello world");
                cmd.Parameters.AddWithValue("p2", DateTime.Now.ToString());
                await cmd.ExecuteNonQueryAsync();
            }

报错：
GaussDBException: Received backend message AuthenticationRequest while expecting AuthenticationRequestMessage. Please file a bug.
An unhandled exception has occurred while executing the request.
      GaussDB.GaussDBException (0x80004005): Received backend message AuthenticationRequest while expecting AuthenticationRequestMessage. Please file a bug.

**Comment by wangpengxpy** [comment]
这个问题可能是连接超时等等导致的貌似，适配验证连接时一直会有同样的异常但已经修复了！给个环境或者官方windows部署我本地抽空验证下看看

**Comment by wangboy91** [comment]
参考 https://gitee.com/opengauss/openGauss-connector-adonet  链接5.1成功 
https://github.com/wangboy91/OpenGauss.NET

**Comment by wangpengxpy** [comment]
该issue提出者未进一步给予反馈，暂关闭 @anhuizf1

**Comment by gogobosco** [comment]
> 参考 https://gitee.com/opengauss/openGauss-connector-adonet 链接5.1成功 https://github.com/wangboy91/OpenGauss.NET

确实解决问题。请问 OpenGauss.NET 有 nuget 包吗？

**Comment by wangboy91** [comment]
空可以我取推一个包
